#!/bin/bash

# AWS allows us to spawn servers with whatever SSH keys we like. Instead of
# hardcoding a particular key in bcfg2, let's get the key from AWS itself
# http://docs.amazonwebservices.com/AWSEC2/latest/UserGuide/AESDG-chapter-instancedata.html

curl -s http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key
